---
version: '2'
services:
  zookeeper:
    image: abhinav054/zookeeper
    container_name: zookeeper-test
    network_mode: "host"
    ports:
      - "2181:2181"
      - "7071:7071"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  kafka:
    build: .
    network_mode: "host"
    ports:
      - "9092:9092"
      - "1099:1099"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: localhost:2181
      KAFKA_JMX_OPTS: "-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=0.0.0.0 -Dcom.sun.management.jmxremote.rmi.port=1099"
      JMX_PORT: 1099
  prometheus:
    image: prom/prometheus
    network_mode: "host"
    ports:
      - 9090:9099/tcp
    volumes:
      - ./mount/prometheus:/etc/prometheus
